# Generated by Django 3.2.25 on 2024-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240706_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(default=''),
        ),
    ]
