# Generated by Django 3.2.25 on 2024-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vacancy_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='skills',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
