# Generated by Django 3.2.25 on 2024-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240706_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='remote_work',
            field=models.BooleanField(default=False),
        ),
    ]
